# Generated by Django 5.2.6 on 2025-09-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_created_at_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_event'], 'permissions': [('can_manage_events', 'Can create, update, delete events')], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': (['email'],), 'permissions': [('can_approve_users', 'Peut approuver les comptes utilisateurs')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
