# Generated by Django 5.2.6 on 2025-09-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': [('can_approve_users', 'Peut approuver les comptes utilisateurs')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
