# Generated by Django 5.2.6 on 2025-10-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='opponent',
            field=models.CharField(blank=True, default=dict, max_length=255, null=True),
        ),
    ]
