# Generated by Django 5.2.6 on 2025-11-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='note',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
