# Generated by Django 5.2.6 on 2025-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_participation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='will_attend',
            field=models.BooleanField(default=True),
        ),
    ]
