# Generated by Django 5.2.6 on 2025-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_participation_will_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='note',
            new_name='buts',
        ),
        migrations.AddField(
            model_name='participation',
            name='cartonJaune',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participation',
            name='cartonRouge',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participation',
            name='passe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participation',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
