# Generated by Django 5.2.6 on 2025-12-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_note_participation_buts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='season_year',
            field=models.CharField(default='2025-2026', max_length=9),
            preserve_default=False,
        ),
    ]
