# Generated by Django 5.2.6 on 2025-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_event_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='opponent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
