# Generated by Django 5.2.6 on 2025-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='opponent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
